name: test and publish

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [push-event]

jobs:
      
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build --configuration Release
      
  test:
    needs: build 
    
    runs-on: ubuntu-latest
    
    steps:  
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Run Unit Tests
      run: |
        docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome 
        dotnet test --verbosity normal
      
  publish:
    needs: [build, test]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.108
      - name: Build with dotnet
        run: dotnet build --configuration Release
      - name: Publish nuget
        run: dotnet nuget push **/*.nupkg -k ${{secrets.NGPackagesToken}} -s https://api.nuget.org/v3/index.json || true
